<?php
/**
 * Created by PhpStorm.
 * User: aldotripiciano
 * Date: 16/05/15
 * Time: 16:45
 */

class Payment extends DataContainer {
  function loadJSON() {
    parent::loadJSON();
  }

  /**
   * @param array $ignore
   */
  function saveJSON($ignore = array()) {
    parent::saveJSON($ignore);
  }

  /**
   * @param array $ignore
   */
  function updateJSON($ignore = array()) {
    parent::updateJSON($ignore);
  }
}
