[FORM|name=shadow-login:
[SHADOW_DESCRIPTION:[TEXT|tag=user-login-preview:Please insert your personal data to enter the system.]]
[INPUT|type=string|required|name=username|id=username|title=[TEXT|tag=user-login-username:Username or Email]:shadow-login]
[INPUT|title=[TEXT|tag=user-login-password:Password]|type=password|required|name=password|id=password:shadow-login]
[INPUT|type=hidden|required|name=action|value=login:shadow-login]
]
