<div class="shadow-inner">
  [MESSAGES]
  <div id="shadow-titles">
    <ul class="shadow-titles-list">[SHADOW:tab-titles]</ul>
  </div>
  <div class="shadow-contents">
    [SHADOW:tab-contents]
    <div class="messages"></div>
    <a onClick="if (confirm('Are you sure you want to update this item?')) shadowSubmit()" id="edit-save" ><span style="color:green">&check;&nbsp;</span>Update</a>

  </div>

</div>
