<?php
require_once("classes/Localization.class.php");

/**
 * Returns a translated version of a string.
 *
 * @param string $string
 *   The translatable string.
 *
 * @param array $replace
 *   An array of replacements to perform in the string.
 *
 * @return string
 *   The translated string.
 */
function t($string, $replace = array()) {
  // TODO: multilanguage strings implementation.
  foreach ($replace as $k => $replacement) {
    $string = str_replace($k, $replacement, $string);
  }
  return $string;
}

