#!/usr/bin/env php
<?php
  if (empty($argv[1])) {
    die("Please enter a Quanta target / host, and a doctor command\n(i.e. doctor mysite.com check)\n");
  }

  $host = $argv[1];
  $doctor_cmd = $argv[2];
  $request_uri = '/doctor/';
  $docroot = getcwd();
  include 'src/boot.php';
