<?php
namespace Quanta\Common;

/**
 * Class FormItemString
 * This class represents a Form Item of type dropdown Select
 */
class FormItemNumber extends FormItemString {
  public $type = 'number';

  function loadAttributes() {
    parent::loadAttributes(); // TODO: Change the autogenerated stub
  }
}
