
<div id="payments" style="display: none">
  <form action="https://www.paypal.com/cgi-bin/webscr" method="post"
        target="_top">
    <input type="hidden" name="cmd" value="_s-xclick">
    <input type="hidden" name="hosted_button_id" value="L4Y7HSRNWW5W6">
    <table>
      <tr>
        <td><input type="hidden" name="on0" value="Select your package">Select
          your package
        </td>
      </tr>
      <tr>
        <td><select name="os0">
            <option value="1000 Shots">1000 Shots $9,99 USD</option>
            <option value="5000 Shots">5000 Shots $29,99 USD</option>
            <option value="10000 Shots">10000 Shots $49,99 USD</option>
          </select></td>
      </tr>
      <tr>
        <td><input type="hidden" name="on1" value="Your NamePumper code">Your
          NameArcher code
        </td>
      </tr>
      <tr>
        <td><input type="text" name="os1" maxlength="200"></td>
      </tr>
    </table>
    <input type="hidden" name="currency_code" value="USD">
    <input type="image"
           src="https://www.paypalobjects.com/it_IT/IT/i/btn/btn_buynow_LG.gif"
           border="0" name="submit"
           alt="PayPal - Il metodo rapido, affidabile e innovativo per pagare e farsi pagare.">
    <img alt="" border="0"
         src="https://www.paypalobjects.com/it_IT/i/scr/pixel.gif" width="1"
         height="1">
  </form>
</div>