<?php
namespace Quanta\Common;

/**
 * Class FormItemUrl
 * This class represents a Form Item of type Url.
 */
class FormItemUrl extends FormItemString {
  public $type = 'url';

  public function loadAttributes() {
    parent::loadAttributes(); // TODO: Change the autogenerated stub
  }

  /**
   * @return string
   */
  public function getHTMLType() {
    return 'url';
  }

  /**
   *
   */
  public function validate() {
    $value = $this->getValue();
    if (!valid_url(array_pop($value))) {
       $this->getForm()->validationError($this, t('Insert a valid URL'));
    };
  }
}
