<?php
require_once("Localization.class.inc");

/**
 * Returns a translated version of a string.
 *
 * @param $string
 *   The translatable string.
 *
 * @return mixed
 *   The translated string.
 */
function t($string, $replace = array()) {
  // TODO: multilanguage strings implementation.
  foreach ($replace as $k => $replacement) {
    $string = str_replace($k, $replacement, $string);
  }
  return $string;

}