<?php
namespace Quanta\Qtags;

/**
 * Class FormItemUrl
 * This class represents a Form Item of type Url.
 */
class FormItemUrl extends FormItemString {
  public $type = 'url';

  public function loadAttributes() {
    parent::loadAttributes(); // TODO: Change the autogenerated stub
  }

  /**
   * @return string
   */
  public function getHTMLType() {
    return 'url';
  }

  /**
   *
   */
  public function validate() {
    $url = $this->getSubmittedValue() ? $this->getSubmittedValue() : $this->getValue(true);
    if (!empty($url) && !\Quanta\Common\Api::valid_url($url)) {
      $this->setValidationStatus(false);
      $translated_text = \Quanta\Common\Localization::translatableText($this->env,'Per favore, inserisci un URL valido!','enter-valid-url-message');
      $this->setValidationMessage($translated_text);
      if($this->getFormState()){ 
          $this->getFormState()->validationError($this->getName(), $translated_text);
      }
    }
    parent::validate();
  }
}
