<h2>Profile of: [USER:name]</h2><form>
  <input type="hidden" id="action" name="action" value="[USER:action]" />
  <input type="hidden" id="edit-name" name="edit-name" value="[USER:name]" />

  <table>
    <tr><td>Your email:</td><td><input id="edit-email" name="edit-email" value="[USER:email]" type="text"></td></tr>
    <tr><td>First name:</td><td><input id="edit-first_name" name = "edit-first_name" value="[USER:first_name]" type="text"></td></tr>
    <tr><td>Last name:</td><td><input id="edit-last_name"  name="edit-last_name" value="[USER:last_name]" type="text"></td></tr>

    <tr><td colspan="2" class="description-row">Do you want to change your password?</td></tr>
    <tr><td>Old password:</td><td><input id="edit-old_password" name="edit-old_password" value="" type="password"></td></tr>
    <tr><td>New password:</td><td><input id="edit-password" name="edit-password" value="" type="password"></td></tr>
    <tr><td>Repeat New password:</td><td><input id="edit-password_rp" name="edit-password_rp" value="" type="password"></td></tr>
  </table>
</form>