<h4>[TEXT|tag=file-operations:Operazioni sulle immagini]</h4>
[FORM|name=shadow-form|id=shadow-form:
    [TEXT|tag=file-operations-desc:Scegli l'azione che desideri applicare all'immagine]
    [INPUT|type=hidden|name=form|value=file_operations:shadow-form]
    [INPUT|type=hidden|id=current_url|required|name=current_url:shadow-form]
    [INPUT|type=hidden|name=img_node|value={SHADOW:img_node}:shadow-form]
    [INPUT|type=hidden|name=img|value={SHADOW:img}:shadow-form]
    [INPUT|id=edit_action|type=hidden|name=action|value=file_operations:shadow-form]
]
