<?php
/*
 * Ideally this module should including as few functions as possible.
 * Functions should mostly be hooks to be included into modules.
 */

/**
 * Return first occurrence of HTML / XML element in a string.
 */
function parsetag($string, $tag) {
  $pattern = "/<" . $tag . ">(.*?)<\/" . $tag . ">/s";
  preg_match_all($pattern, $string, $matches);
  return isset($matches[1][0]) ? $matches[1][0] : '';
}

/**
 * Generate a password
 */
function pwd($pass) {
  return substr((md5(substr($pass, 0, 5) . 'ABC' . substr($pass, 5, 2) . 'nginE')) . md5($pass), 0, 50);
  
}

// TODO: make this stuff better.
function redirect($where) {
  print '<script>top.location.href="' . $where . '";</script>';
}

function is_alphanumeric($string) {
  return preg_match('/^[A-Za-z0-9_]+$/', $string);
}

function valid_email($string) {
  return (!filter_var($string, FILTER_VALIDATE_EMAIL) === FALSE);

  }

function valid_url($string) {
  return (!filter_var($string, FILTER_VALIDATE_URL) === FALSE);

  }

function string_normalize($string) {
  $string = str_replace('[', '&lbrack;', $string);
  $string = str_replace(']', '&rbrack;', $string);
  $string = str_replace('{', '&lbrace;', $string);
  $string = str_replace('}', '&rbrace;', $string);
  $string = str_replace(':', '&colon;', $string);
  $string = str_replace('|', '&verbar;', $string);
  // $string = str_replace('=', '&equals;', $string);
  // Remove tabs and newlines.
  // TODO: was necessary as it broke INPUT tags by weirdly printing the value...
  return preg_replace('~[\r\n\t]+~', '', $string);
}