Oh no, you have finished your energy and can't spot new domains! Now what?<br/>
No worries, here are several ways to recharge your energy.<br/><br/>

1) You can buy a full recharge right now. <b>It costs always and only 9.99$</b> regardless your level!<br/><br/>

2) Every day you get a number of free energy (your level * 100)<br/><br/>

3) You can shoot some of your spotted domains. Every time someone registers a domain you shooted, you will get a boost in your charge!<br/><br/>

4) Someone can donate you his energy

